package com.dlrjsgml.memoa.remote

object TemporaryToken {
    var AccessToken : String = "eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsImVtYWlsIjoibGVlZ2VoMTIxM0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZGV2aWNlIjoib2todHRwLzQuMTIuMF8yMjEuMTY4LjIyLjIwNSIsImlhdCI6MTczMTMxNjk0OSwiZXhwIjoxNzMxMzE3NTQ5fQ.akukI8XwoBJfgH7XmfjNkYbi9n1DoRY8DPQZrUREg_s"
}