package com.dlrjsgml.memoa.remote

object TemporaryToken {
    var AccessToken : String = "eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsImVtYWlsIjoibGVlZ2VoMTIxM0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZGV2aWNlIjoiTW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTBfMTVfNykgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEzMC4wLjAuMCBTYWZhcmkvNTM3LjM2XzIyMS4xNjguMjIuMjA1IiwiaWF0IjoxNzMwNzE1NjMyLCJleHAiOjE3MzA3MTYyMzJ9.iuLvprVOGpmSSz8RzCZknEdrRmhHYJCK0NDe7eCknM0"
}