package com.dlrjsgml.memoa.remote

object TemporaryToken {
    var AccessToken : String = "eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsImVtYWlsIjoibGVlZ2VoMTIxM0BnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiZGV2aWNlIjoib2todHRwLzQuMTIuMF8yMjEuMTY4LjIyLjIwNSIsImlhdCI6MTczMTMyMjUxMCwiZXhwIjoxNzMxMzIzMTEwfQ.8u6ytAR3g6NlxRFB1jPCC8it4mcCBiI6OFOwrXjYIOM"
}